CREATE TABLE `trades` (
	`id` text PRIMARY KEY NOT NULL,
	`ticker` text NOT NULL,
	`entry_price` real NOT NULL,
	`exit_price` real,
	`entry_date` text NOT NULL,
	`exit_date` text,
	`size` real NOT NULL,
	`direction` text NOT NULL,
	`asset_type` text NOT NULL,
	`trade_type` text,
	`fees` real DEFAULT 0,
	`strategy` text,
	`notes` text,
	`screenshot_url` text,
	`is_draft` integer DEFAULT false,
	`option_type` text,
	`strike` real,
	`expiration_date` text,
	`contracts` integer,
	`premium_entry` real,
	`premium_exit` real,
	`created_at` text DEFAULT '2026-03-09T00:31:53.906Z' NOT NULL,
	`updated_at` text DEFAULT '2026-03-09T00:31:53.907Z' NOT NULL
);
